{
    "0": {
        "Test Input": "TypeError: Connect() with one argument",
        "The Closest": {
            "ID": 6536,
            "Words": "typeerror connect take exactli one argument"
        },
        "Second Closest": {
            "ID": 21025,
            "Words": "cqlsh connect error ref take keyword argument"
        }
    },
    "1": {
        "Test Input": "ModuleNot FoundError virtual",
        "The Closest": {
            "ID": 15682,
            "Words": "error instal shap packag virtual environ pycharm mac"
        },
        "Second Closest": {
            "ID": 2732,
            "Words": "conda report reticul environ"
        }
    },
    "2": {
        "Test Input": "ValueError: NumPy bool array can\u2019t assign 100 input to 90 output where mask true",
        "The Closest": {
            "ID": 542,
            "Words": "xarray assign coordin dimens"
        },
        "Second Closest": {
            "ID": 861,
            "Words": "mypi error incompat type assign"
        }
    },
    "3": {
        "Test Input": "Pandas data frame unhashable type error",
        "The Closest": {
            "ID": 5293,
            "Words": "unsupport operand type error use"
        },
        "Second Closest": {
            "ID": 1091,
            "Words": "error read data csv file use panda"
        }
    },
    "4": {
        "Test Input": "Google-trans-new throws an error on previously working code in Python",
        "The Closest": {
            "ID": 6540,
            "Words": "googl tran new throw error code work"
        },
        "Second Closest": {
            "ID": 4224,
            "Words": "webscrap problem return error googl collab"
        }
    },
    "5": {
        "Test Input": "AttributeError: The'str' object does not have the 'rotation' attribute",
        "The Closest": {
            "ID": 14294,
            "Words": "xlsxwriter attributeerror str object attribut add_worksheet"
        },
        "Second Closest": {
            "ID": 9759,
            "Words": "attributeerror quantumcircuit object attribut config"
        }
    },
    "6": {
        "Test Input": "ERROR: During the installation of pyaudio, the command failed with an exit status of 1",
        "The Closest": {
            "ID": 17388,
            "Words": "error instal pyarrow"
        },
        "Second Closest": {
            "ID": 7309,
            "Words": "error instal linearmodel packag jupyt notebook"
        }
    },
    "7": {
        "Test Input": "Python win32ui.error:\u00a0CreateCompatibleDC failed with an error.",
        "The Closest": {
            "ID": 14747,
            "Words": "http client get request tmdb api fail error"
        },
        "Second Closest": {
            "ID": 7860,
            "Words": "nltk stopword fail lookuperror"
        }
    },
    "8": {
        "Test Input": "Attempts to'requests.\u2019get have resulted in several failures for Python API",
        "The Closest": {
            "ID": 6544,
            "Words": "mani error tri request get api"
        },
        "Second Closest": {
            "ID": 17094,
            "Words": "error typeerror firstform miss requir posit argument request"
        }
    },
    "9": {
        "Test Input": "Import error while using custom modules in Python 3",
        "The Closest": {
            "ID": 7198,
            "Words": "import error use tensorflow import lstm model"
        },
        "Second Closest": {
            "ID": 18886,
            "Words": "import error import msgpackseri"
        }
    },
    "10": {
        "Test Input": "When I try to extract json information from a website, Python throws a keyword",
        "The Closest": {
            "ID": 6546,
            "Words": "throw keyword error tri get json metadata websit"
        },
        "Second Closest": {
            "ID": 9939,
            "Words": "error invalid json syntax offset receiv error tri get everflow report"
        }
    },
    "11": {
        "Test Input": "to_sql pyodbc count field invalid or syntax error",
        "The Closest": {
            "ID": 19256,
            "Words": "error join two tabl use sqlalchemi"
        },
        "Second Closest": {
            "ID": 6547,
            "Words": "to_sql pyodbc count field incorrect syntax error"
        }
    },
    "12": {
        "Test Input": "Argument 1 has the unexpected type 'QPushButton,' which causes TypeError",
        "The Closest": {
            "ID": 6548,
            "Words": "type error argument unexpect type qpushbutton"
        },
        "Second Closest": {
            "ID": 11009,
            "Words": "tri make balanc command discord py work give unexpect error"
        }
    },
    "13": {
        "Test Input": "I'm trying to conduct analysis with Jupyter, and I've tried the code below, but I get a NameError instead. I defined df while starting",
        "The Closest": {
            "ID": 6549,
            "Words": "tri use jupyt run analysi run code get nameerror instead defin df begin"
        },
        "Second Closest": {
            "ID": 15253,
            "Words": "ignor nameerror continu run rest program"
        }
    },
    "14": {
        "Test Input": "python openpyxl.load_workbook\u00a0TypeError: No arguments are sent to Fill()",
        "The Closest": {
            "ID": 15213,
            "Words": "remov error argument pars"
        },
        "Second Closest": {
            "ID": 18370,
            "Words": "openpyxl write row result typeerror"
        }
    },
    "15": {
        "Test Input": "Error: unsupported operand type(s) for >>: 'list' and 'list' in airflow DAG. Tasks are executed\u00a0in a sequential and parallel manner.",
        "The Closest": {
            "ID": 6551,
            "Words": "get error airflow dag unsupport operand type list list sequenti parallel execut task"
        },
        "Second Closest": {
            "ID": 2366,
            "Words": "pytorch gradient error nonetyp unsupport operand type nonetyp nonetyp"
        }
    },
    "16": {
        "Test Input": "SOLVED Error Fixing: \"InvalidArgumentError: All inputs must match\u00a0the same shape: values[0]. shape = [16] != values[1].shape = [64]",
        "The Closest": {
            "ID": 6552,
            "Words": "solv fix error shape input must match valu shape valu shape"
        },
        "Second Closest": {
            "ID": 1377,
            "Words": "solv valueerror must size issu"
        }
    },
    "17": {
        "Test Input": "ParserError: Data tokenization error. \u00a0C error:\u00a0 EOF inside string beginning at row 110994 1",
        "The Closest": {
            "ID": 6553,
            "Words": "parsererror error token data error eof insid string start row \u00e4\u00e3"
        },
        "Second Closest": {
            "ID": 11172,
            "Words": "jsondecodeerror use loop"
        }
    },
    "18": {
        "Test Input": "View the image using the scroll bar, Canvas on Canvas. This error is thrown: 1 mandatory positional argument is missing from item configure (): 'tagOrId'",
        "The Closest": {
            "ID": 3187,
            "Words": "chang categori channel permiss return error miss permiss novu discord py"
        },
        "Second Closest": {
            "ID": 21083,
            "Words": "error decod byte send imag discord"
        }
    },
    "19": {
        "Test Input": "I keep getting an error when I try to remove \\n\u00a0from my list",
        "The Closest": {
            "ID": 4880,
            "Words": "attributeerror nonetyp object attribut gettext"
        },
        "Second Closest": {
            "ID": 2818,
            "Words": "googl api oauth error"
        }
    },
    "20": {
        "Test Input": "After generating a dataframe from a list of dictionaries, TypeError: no numeric data to plot",
        "The Closest": {
            "ID": 1240,
            "Words": "issu typeerror loop column list data frame"
        },
        "Second Closest": {
            "ID": 4268,
            "Words": "divid data frame column get float divis zero"
        }
    },
    "21": {
        "Test Input": "Keras: AttributeError: The 'Sequential' object does not have the '_nested inputs' attribute",
        "The Closest": {
            "ID": 6477,
            "Words": "joblib return typeerror pickl weakref object code differ input data"
        },
        "Second Closest": {
            "ID": 9787,
            "Words": "attributeerror nonetyp object attribut get_text input id"
        }
    },
    "22": {
        "Test Input": "NameError: name 'tk' is not defined in Python tkinter",
        "The Closest": {
            "ID": 10441,
            "Words": "nameerror name defin"
        },
        "Second Closest": {
            "ID": 9030,
            "Words": "nameerror name input_shap defin"
        }
    },
    "23": {
        "Test Input": "When using pygooglenews, there is an Attribute error: the 'list' object has no attribute 'strftime'",
        "The Closest": {
            "ID": 4451,
            "Words": "attribut error list object attribut checkclick"
        },
        "Second Closest": {
            "ID": 24134,
            "Words": "attributeerror list object attribut titl"
        }
    },
    "24": {
        "Test Input": "requests.exceptions. When my Python script discovers an offline website, it throws a ConnectionError: HTTPConnectionPool error",
        "The Closest": {
            "ID": 6560,
            "Words": "request except connectionerror error script find websit offlin"
        },
        "Second Closest": {
            "ID": 24153,
            "Words": "atom give error request data websit"
        }
    },
    "25": {
        "Test Input": "ValueError: When using keras to do regression for integer values that include negatives, no gradients are provided for any variable",
        "The Closest": {
            "ID": 6561,
            "Words": "valueerror gradient provid variabl regress integ valu includ neg use kera"
        },
        "Second Closest": {
            "ID": 22878,
            "Words": "strang errro valueerror shape pass valu indic impli"
        }
    },
    "26": {
        "Test Input": "When importing classes from a jar, Jpype throws a ModuleNotFoundError",
        "The Closest": {
            "ID": 6562,
            "Words": "jpype import class jar"
        },
        "Second Closest": {
            "ID": 16237,
            "Words": "quantlib hestonmodelhelp class throw error"
        }
    },
    "27": {
        "Test Input": "Unknown loss function in Keras custom loss error",
        "The Closest": {
            "ID": 10818,
            "Words": "discord py error unknown messag"
        },
        "Second Closest": {
            "ID": 18610,
            "Words": "cerberu schema schemaerror uuid unknown rule"
        }
    },
    "28": {
        "Test Input": "How to only run\u00a0a pytest fixture cleanup if the test fails or fails with an error",
        "The Closest": {
            "ID": 15476,
            "Words": "stop pytest error fail"
        },
        "Second Closest": {
            "ID": 8946,
            "Words": "deprecationwarn elementwis comparison fail rais error futur"
        }
    },
    "29": {
        "Test Input": "Although there is a replit error\u00a0with the google API, it works in Pycharm",
        "The Closest": {
            "ID": 6565,
            "Words": "replit error googl api work pycharm"
        },
        "Second Closest": {
            "ID": 388,
            "Words": "descript flake error pycharm"
        }
    },
    "30": {
        "Test Input": "jinja2.exceptions.UndefinedError:\u00a0 'function' is not\u00a0defined",
        "The Closest": {
            "ID": 16144,
            "Words": "user defin except error use tri except"
        },
        "Second Closest": {
            "ID": 2978,
            "Words": "error cookielib defin mean cookiejar"
        }
    },
    "31": {
        "Test Input": "An AttributeErrorr occurs when SQLAlchemy is installed with Poetry",
        "The Closest": {
            "ID": 14766,
            "Words": "modul name sqlalchemi conda packag manag"
        },
        "Second Closest": {
            "ID": 6567,
            "Words": "instal sqlalchemi poetri caus attributeerrorr"
        }
    },
    "32": {
        "Test Input": "After a few successful Selenium Geckodriver tasks, the connection was refused (os error 111)\u00a0(Python)",
        "The Closest": {
            "ID": 6568,
            "Words": "connect refus os error success selenium geckodriv task"
        },
        "Second Closest": {
            "ID": 19989,
            "Words": "space left devic error docker run selenium scraper"
        }
    },
    "33": {
        "Test Input": "Is there any way to escape\u00a0the error and move on to the next word?",
        "The Closest": {
            "ID": 6569,
            "Words": "way escap error go next word"
        },
        "Second Closest": {
            "ID": 8296,
            "Words": "winerror system find file specifi sublim text code"
        }
    },
    "34": {
        "Test Input": "How to remove items from a Python list that begin with a specific string without getting an AttributeError: The 'startswith' attribute is missing from the 'NoneType' object",
        "The Closest": {
            "ID": 19046,
            "Words": "null entri databs click get typeerror admin user personal_detail chang return non string type nonetyp"
        },
        "Second Closest": {
            "ID": 5239,
            "Words": "updat tupl string element error"
        }
    },
    "35": {
        "Test Input": "pycuda._driver.LogicError: cuModuleLoadDataEx given by pyCUDA with Flask",
        "The Closest": {
            "ID": 6586,
            "Words": "name given modul error flask"
        },
        "Second Closest": {
            "ID": 23110,
            "Words": "flask function take error argument"
        }
    },
    "36": {
        "Test Input": "When using Beautiful Soup to access ['style'], a KeyError occurs",
        "The Closest": {
            "ID": 6572,
            "Words": "keyerror tri access style use beauti soup"
        },
        "Second Closest": {
            "ID": 8119,
            "Words": "beauti soup keyerror href definit exist"
        }
    },
    "37": {
        "Test Input": "When using Flask, a PyCUDA context error happens",
        "The Closest": {
            "ID": 6573,
            "Words": "pycuda context error use flask"
        },
        "Second Closest": {
            "ID": 7244,
            "Words": "permissionerror errno permiss deni flask run"
        }
    },
    "38": {
        "Test Input": "Mercurial error *** failed to import extension hggit: hggit is not a module",
        "The Closest": {
            "ID": 18919,
            "Words": "fail pdb main"
        },
        "Second Closest": {
            "ID": 2246,
            "Words": "give jwt except signatur verif fail error"
        }
    },
    "39": {
        "Test Input": "The view leads.views.home_page did not return a HttpResponse object, resulting in a ValueError. Instead, it returned None how to fix a python django template error",
        "The Closest": {
            "ID": 6575,
            "Words": "valueerror view lead view home_pag return httprespons object return none instead django templat error fix"
        },
        "Second Closest": {
            "ID": 9893,
            "Words": "valueerror view return httprespons object return none instead django imgkit"
        }
    },
    "40": {
        "Test Input": "Windows 10 pip install dotenv error code 1",
        "The Closest": {
            "ID": 6576,
            "Words": "pip instal dotenv error code window"
        },
        "Second Closest": {
            "ID": 4472,
            "Words": "origin error discord bot code"
        }
    },
    "41": {
        "Test Input": "SQL Server Python ML Services FileNotFoundError",
        "The Closest": {
            "ID": 6577,
            "Words": "sql server ml servic"
        },
        "Second Closest": {
            "ID": 16206,
            "Words": "valueerror titan pipelin"
        }
    },
    "42": {
        "Test Input": "django gunicorn.errors.HaltServer: <HaltServer 'Worker ended in failure for booting.\u2019 3>",
        "The Closest": {
            "ID": 22829,
            "Words": "celeri workerlosterror worker exit prematur signal sigabrt"
        },
        "Second Closest": {
            "ID": 9401,
            "Words": "anyon help identifi heroku applic error"
        }
    },
    "43": {
        "Test Input": "When extracting month from date strings with single digit months, Pandas throws a ValueError: incorrect literal for int() with base 10: '1/'.",
        "The Closest": {
            "ID": 6579,
            "Words": "panda valueerror invalid liter int base extract month date string singl digit month"
        },
        "Second Closest": {
            "ID": 9040,
            "Words": "panda astyp throw invalid liter int base error"
        }
    },
    "44": {
        "Test Input": "sklearn.model_selection.train_test_split",
        "The Closest": {
            "ID": 4857,
            "Words": "sklearn jupyt notebook"
        },
        "Second Closest": {
            "ID": 10533,
            "Words": "sklearn typeerror got unexpect keyword argument n_split"
        }
    },
    "45": {
        "Test Input": "of (Invalid arguments) from stratify method error",
        "The Closest": {
            "ID": 6580,
            "Words": "error invalid paramet stratifi method sklearn model_select"
        },
        "Second Closest": {
            "ID": 10202,
            "Words": "error mean invalid elf header"
        }
    },
    "46": {
        "Test Input": "If my program receives three consecutive zeros, it should stop accepting input and produce an error message.\u00a0 I don't understand\u00a0how to put the condition into action",
        "The Closest": {
            "ID": 6581,
            "Words": "want program stop take input get three consecut zero print error messag understand implement condit"
        },
        "Second Closest": {
            "ID": 10085,
            "Words": "typeerror concaten str int str use len input print"
        }
    },
    "47": {
        "Test Input": "Remove a single quotation mark from each entry in the list in Python. AttributeError: The 'list' object does not have the 'split' attribute",
        "The Closest": {
            "ID": 6582,
            "Words": "remov singl quotat mark element list attributeerror list object attribut split"
        },
        "Second Closest": {
            "ID": 10194,
            "Words": "attributeerror list object attribut replac"
        }
    },
    "48": {
        "Test Input": "\"Got a KeyError on serializer AssetSerializer when trying to acquire a value for field devUserId. 'devUserId' was the original exception text",
        "The Closest": {
            "ID": 6583,
            "Words": "got keyerror attempt get valu field devuserid serial assetseri origin except text devuserid"
        },
        "Second Closest": {
            "ID": 11523,
            "Words": "tri except valu error name error"
        }
    },
    "49": {
        "Test Input": "Due to a TypeError, Pandas groupby\u00a0cannot concatenate strings",
        "The Closest": {
            "ID": 23178,
            "Words": "dask concaten caus memori error panda concaten file"
        },
        "Second Closest": {
            "ID": 12090,
            "Words": "unabl creat histogram slice due datetim datatyp error"
        }
    },
    "50": {
        "Test Input": "ImportError: The name 'ImageTK' cannot be imported",
        "The Closest": {
            "ID": 10295,
            "Words": "importerror modul name cycler"
        },
        "Second Closest": {
            "ID": 1468,
            "Words": "flask app importerror run docker"
        }
    },
    "51": {
        "Test Input": "python error: no name in the provided module (flask)",
        "The Closest": {
            "ID": 7244,
            "Words": "permissionerror errno permiss deni flask run"
        },
        "Second Closest": {
            "ID": 23819,
            "Words": "flask permissionerror errno permiss deni"
        }
    },
    "52": {
        "Test Input": "After overriding the __add__ method, a TypeError occurs",
        "The Closest": {
            "ID": 6587,
            "Words": "typeerror overrid method"
        },
        "Second Closest": {
            "ID": 13970,
            "Words": "catch error use isbnlib meta method continu"
        }
    },
    "53": {
        "Test Input": "my OneToOneField relationship has a ValueError: Cannot assign User",
        "The Closest": {
            "ID": 6588,
            "Words": "valueerror assign user issu onetoonefield relationship"
        },
        "Second Closest": {
            "ID": 9678,
            "Words": "valueerror createpost assign django contrib auth model anonymousus"
        }
    },
    "54": {
        "Test Input": "OperationalError in psycopg2",
        "The Closest": {
            "ID": 20738,
            "Words": "read gekko error code posit etc"
        },
        "Second Closest": {
            "ID": 14572,
            "Words": "remov bad magic number error pyinstal"
        }
    },
    "55": {
        "Test Input": "mistake when converting a matrix from a text file to a numpy matrix",
        "The Closest": {
            "ID": 18977,
            "Words": "numpi loadtxt handl text encod relat follow error"
        },
        "Second Closest": {
            "ID": 25020,
            "Words": "keep get error sure convert set object str implicitli"
        }
    },
    "56": {
        "Test Input": "trying to run the module, but getting a syntax error",
        "The Closest": {
            "ID": 2156,
            "Words": "syntax error tri instal agentpi"
        },
        "Second Closest": {
            "ID": 20639,
            "Words": "get syntax error use speech recoginit"
        }
    },
    "57": {
        "Test Input": "FileNotFoundError: [Errno 2] in Python/Docker There isn't a file or directory with that name:",
        "The Closest": {
            "ID": 3353,
            "Words": "fitz modul name frontend error docker"
        },
        "Second Closest": {
            "ID": 6592,
            "Words": "docker errno file directori"
        }
    },
    "58": {
        "Test Input": "error while compiling pip: AttributeError: The 'ParsedRequirement' object does not have the 'editable' attribute",
        "The Closest": {
            "ID": 6593,
            "Words": "pip compil error attributeerror parsedrequir object attribut edit"
        },
        "Second Closest": {
            "ID": 19770,
            "Words": "attributeerror modul pip download attribut httpadapt"
        }
    },
    "59": {
        "Test Input": "Django - AttributeError: 'int' object has no attribute 'pk'",
        "The Closest": {
            "ID": 6594,
            "Words": "attributeerror int object attribut pk django"
        },
        "Second Closest": {
            "ID": 22023,
            "Words": "drf attributeerror int object attribut pk"
        }
    },
    "60": {
        "Test Input": "How do I fix this problem\u00a0\"AttributeError: No attribute 'gethostname' in module 'socket'\"",
        "The Closest": {
            "ID": 6595,
            "Words": "fix error attributeerror modul socket attribut gethostnam"
        },
        "Second Closest": {
            "ID": 1380,
            "Words": "attributeerror type object socket attribut socket"
        }
    },
    "61": {
        "Test Input": "How can I fix the Error\u00a0DetailView is lacking a QuerySet?",
        "The Closest": {
            "ID": 24250,
            "Words": "fix regist namespac django error"
        },
        "Second Closest": {
            "ID": 23918,
            "Words": "fix django rest framework templat"
        }
    },
    "62": {
        "Test Input": "NameError: 'WebDriverWait' is not a valid name",
        "The Closest": {
            "ID": 12937,
            "Words": "nameerror link list data structur"
        },
        "Second Closest": {
            "ID": 21338,
            "Words": "nameerror load content npz file"
        }
    },
    "63": {
        "Test Input": "Error binding parameter 1 - presumably invalid type sqlite3.InterfaceError",
        "The Closest": {
            "ID": 4909,
            "Words": "sqlalchemi invalid sql data type error"
        },
        "Second Closest": {
            "ID": 4096,
            "Words": "django compress error invalid input type cachekey"
        }
    },
    "64": {
        "Test Input": "How can I import a favicon from the react build folder into a Django server? error\u00a0manifest.json could not be found",
        "The Closest": {
            "ID": 6599,
            "Words": "load favicon django server react build folder manifest json found error"
        },
        "Second Closest": {
            "ID": 1308,
            "Words": "docker importerror import name json itsdanger"
        }
    },
    "65": {
        "Test Input": "python manage.py runserver - strange error (Exception in thread django-main-thread)",
        "The Closest": {
            "ID": 6600,
            "Words": "weird error manag py runserv except thread django main thread"
        },
        "Second Closest": {
            "ID": 14783,
            "Words": "graphql core next wrap except graphqlerror twice"
        }
    },
    "66": {
        "Test Input": "how to proceed: TextIOWrapper is not a valid JSON object; it must be str, bytes, or bytearray",
        "The Closest": {
            "ID": 8168,
            "Words": "json dump fail must unicod str typeerror"
        },
        "Second Closest": {
            "ID": 442,
            "Words": "fastapi pydant json object insid json object valid error"
        }
    },
    "67": {
        "Test Input": "Why am I getting an error that the 'str' objet is not callable?",
        "The Closest": {
            "ID": 6602,
            "Words": "get str objet callabl error"
        },
        "Second Closest": {
            "ID": 22476,
            "Words": "typeerror str callabl"
        }
    },
    "68": {
        "Test Input": "ImportError: 'setuptools.build meta' is not a module",
        "The Closest": {
            "ID": 23479,
            "Words": "travi build importerror modul name gdal"
        },
        "Second Closest": {
            "ID": 23510,
            "Words": "googl api malfunct importerror import name build"
        }
    },
    "69": {
        "Test Input": "How can I solve the 'NoneType' object having no attribute 'strip' Attribute Error",
        "The Closest": {
            "ID": 24108,
            "Words": "solv error attributeerror nonetyp object attribut"
        },
        "Second Closest": {
            "ID": 16255,
            "Words": "solv object attribut action error"
        }
    },
    "70": {
        "Test Input": "Python 3.6.9 has an import problem from the parent directory",
        "The Closest": {
            "ID": 6887,
            "Words": "import anoth directori"
        },
        "Second Closest": {
            "ID": 6605,
            "Words": "import error parent directori"
        }
    },
    "71": {
        "Test Input": "Having an excessive number of uwsgi OSError messages",
        "The Closest": {
            "ID": 6606,
            "Words": "mani uwsgi oserror messag"
        },
        "Second Closest": {
            "ID": 17151,
            "Words": "virtualenv oserror setuptool pip wheel fail error code"
        }
    },
    "72": {
        "Test Input": "uwsgi: OSError: write problem while GET request",
        "The Closest": {
            "ID": 6607,
            "Words": "uwsgi oserror write error get request"
        },
        "Second Closest": {
            "ID": 212,
            "Words": "get connect abort oserror error error request"
        }
    },
    "73": {
        "Test Input": "Error in Python Web Scraping with No Warning",
        "The Closest": {
            "ID": 19276,
            "Words": "mistak code error"
        },
        "Second Closest": {
            "ID": 753,
            "Words": "qpid proton depend build error window"
        }
    },
    "74": {
        "Test Input": "There is no attribute 'contrib' in the module \u00a0'tensorflow_core.compat.v1' AttributeError",
        "The Closest": {
            "ID": 10391,
            "Words": "attributeerror modul kera optim attribut rmsprop"
        },
        "Second Closest": {
            "ID": 7853,
            "Words": "attributeerror modul torch nn attribut reflectionpad"
        }
    },
    "75": {
        "Test Input": "No module called <appname>.url exists ModuleError",
        "The Closest": {
            "ID": 12620,
            "Words": "call modul modul attributeerror boxcar object attribut dice"
        },
        "Second Closest": {
            "ID": 14000,
            "Words": "subprocess call window return error find file"
        }
    },
    "76": {
        "Test Input": "When I try to extract only two substrings from a regex pattern, I get ValueError: too many values to unpack (expected 2)",
        "The Closest": {
            "ID": 5525,
            "Words": "date pattern whatsapp chat text file hour format split error mani valu unpack"
        },
        "Second Closest": {
            "ID": 5838,
            "Words": "extract substr use regex pattern give valueerror mani valu unpack expect"
        }
    },
    "77": {
        "Test Input": "Flask sqlalchemy is what I want to utilize. I\u00a0however\u00a0get a ModuleNotFoundError",
        "The Closest": {
            "ID": 8587,
            "Words": "discord py sqlite warn command db error"
        },
        "Second Closest": {
            "ID": 13208,
            "Words": "flask sqlalchemi error say tabl column name"
        }
    },
    "78": {
        "Test Input": "usage\u00a0of self.master.master. Is excessively a sign of a program structural error?",
        "The Closest": {
            "ID": 3013,
            "Words": "nameerror name self defin"
        },
        "Second Closest": {
            "ID": 7572,
            "Words": "nameerror name raw_input defin"
        }
    },
    "79": {
        "Test Input": "TypeError: object AccessToken can't be used in 'await' expression in python async upload_blob",
        "The Closest": {
            "ID": 6614,
            "Words": "async upload_blob typeerror object accesstoken use await express"
        },
        "Second Closest": {
            "ID": 7058,
            "Words": "discord py typeerror object lock use await express"
        }
    },
    "80": {
        "Test Input": "When combining two df in pandas, ValueError: Shape of passed values is (6, 6), indices indicate (4, 6) error",
        "The Closest": {
            "ID": 18696,
            "Words": "panda join valu error shape pass valu inconsist"
        },
        "Second Closest": {
            "ID": 23262,
            "Words": "use cascaded_union combin shape give valueerror shape geometri creat null valu"
        }
    },
    "81": {
        "Test Input": "How can I fix the TypeError: string indices must be integers in my code?",
        "The Closest": {
            "ID": 22215,
            "Words": "fix typeerror unsupport operand type"
        },
        "Second Closest": {
            "ID": 20466,
            "Words": "fix scyther wx splashscreen error"
        }
    },
    "82": {
        "Test Input": "pandas to_datetime has a KeyError",
        "The Closest": {
            "ID": 8155,
            "Words": "panda pivot_t keyerror"
        },
        "Second Closest": {
            "ID": 6617,
            "Words": "keyerror panda to_datetim"
        }
    },
    "83": {
        "Test Input": "(2003, \"Did not connect to MySQL server on rds.amazonaws.com (110)\") Amazon RDS: OperationalError",
        "The Closest": {
            "ID": 6618,
            "Words": "amazon rd connect mysql server rd amazonaw com"
        },
        "Second Closest": {
            "ID": 7354,
            "Words": "error connect outlook via com"
        }
    },
    "84": {
        "Test Input": "Flask(__name__) = app The 'module' object is not callable, which causes a TypeError",
        "The Closest": {
            "ID": 7577,
            "Words": "mypi type error union callabl list callabl convert list callabl"
        },
        "Second Closest": {
            "ID": 1060,
            "Words": "importerror import name callabl traitlet"
        }
    },
    "85": {
        "Test Input": "Celery NoneType Error in Pytest, Flask, and Celery",
        "The Closest": {
            "ID": 6620,
            "Words": "pytest flask celeri celeri nonetyp error"
        },
        "Second Closest": {
            "ID": 1708,
            "Words": "django schedul nonetyp error custom function"
        }
    },
    "86": {
        "Test Input": "Module 'datetime' has no attribute 'today' | datetime | AttributeError",
        "The Closest": {
            "ID": 19643,
            "Words": "attributeerror modul object attribut getlogg"
        },
        "Second Closest": {
            "ID": 24582,
            "Words": "attributeerror modul fuzzywuzzi attribut ratio"
        }
    },
    "87": {
        "Test Input": "Is there a reason that in Python, something like 'list[]' raises a 'SyntaxError'?",
        "The Closest": {
            "ID": 6622,
            "Words": "reason someth like list rais syntaxerror"
        },
        "Second Closest": {
            "ID": 2226,
            "Words": "sql case like script result typeerror dict sequenc"
        }
    },
    "88": {
        "Test Input": "In Jupyter Notebook an error occurred when performing Gaussian Naive Bayes",
        "The Closest": {
            "ID": 24555,
            "Words": "occur attempt fit cnn model kera"
        },
        "Second Closest": {
            "ID": 21172,
            "Words": "jupyt notebook winerror connect attempt fail connect parti properli respond period time"
        }
    },
    "89": {
        "Test Input": "TypeError: 'int' object is not callable, giving same names to different variables?",
        "The Closest": {
            "ID": 6634,
            "Words": "typeerror int object callabl assign equal name diff variabl"
        },
        "Second Closest": {
            "ID": 22918,
            "Words": "concaten string variabl give typeerror unsupport operand tag"
        }
    },
    "90": {
        "Test Input": "When I use a dictionary to translate numbers written in Spanish words to numeric characters, I get a KeyError: 'y'. What should I do to solve?",
        "The Closest": {
            "ID": 6624,
            "Words": "use dictionari convert number written spanish word numer charact give keyerror solv"
        },
        "Second Closest": {
            "ID": 19069,
            "Words": "longest substr without repeat charact keyerror"
        }
    },
    "91": {
        "Test Input": "Pyspark Py4JJavaError: While attempting to use IDF, an error occurred while calling o401.fit",
        "The Closest": {
            "ID": 24555,
            "Words": "occur attempt fit cnn model kera"
        },
        "Second Closest": {
            "ID": 6625,
            "Words": "pyspark py jjavaerror error occur call fit tri use idf"
        }
    },
    "92": {
        "Test Input": "During the installation of eventlet, the command 'gcc' failed with exit status 1",
        "The Closest": {
            "ID": 12583,
            "Words": "error instal mglearn"
        },
        "Second Closest": {
            "ID": 1968,
            "Words": "error pydictionari would instal"
        }
    },
    "93": {
        "Test Input": "When using the Python client for the Google service account file cache, \"ImportError: file cache is unavailable\"",
        "The Closest": {
            "ID": 23979,
            "Words": "attempt publish azur function app fail repositori longer releas file error"
        },
        "Second Closest": {
            "ID": 18979,
            "Words": "ioerror errno read file system error googl app engin"
        }
    },
    "94": {
        "Test Input": "Why do I get the message \"NameError: global name 'climbStairs' is not defined\" in leetcode? but operates\u00a0without the words'self' and 'object'?",
        "The Closest": {
            "ID": 14033,
            "Words": "nameerror tri use file oper"
        },
        "Second Closest": {
            "ID": 7617,
            "Words": "type hint return nameerror name datetim defin"
        }
    },
    "95": {
        "Test Input": "sqlalchemy.exc.InvalidRequestError:\u00a0 Mapper without property",
        "The Closest": {
            "ID": 13156,
            "Words": "sqlalchemi exc mapper map class room room properti room"
        },
        "Second Closest": {
            "ID": 5074,
            "Words": "syntact error print class properti"
        }
    },
    "96": {
        "Test Input": "django.db.utils.OperationalError: 1005, 'Table `xyz` cannot be created.`#sql-600_237` (errno: 150 \"Foreign key constraint is not formed correctly\")",
        "The Closest": {
            "ID": 21988,
            "Words": "error uniqu constraint match given key referenc tabl although primari key includ"
        },
        "Second Closest": {
            "ID": 11687,
            "Words": "django integrityerror edit valu referenc foreign key"
        }
    },
    "97": {
        "Test Input": "MissingSectionHeaderError: There are no section headers in the file (configparser)",
        "The Closest": {
            "ID": 6631,
            "Words": "file contain section header configpars"
        },
        "Second Closest": {
            "ID": 3145,
            "Words": "error get valu php file request"
        }
    },
    "98": {
        "Test Input": "When the server stops the connection, Firefox displays a connection reset error",
        "The Closest": {
            "ID": 23852,
            "Words": "get except would connect releas help fix"
        },
        "Second Closest": {
            "ID": 21511,
            "Words": "pyqt click connect work error"
        }
    },
    "99": {
        "Test Input": "While using np.random.randint(), numba.core.errors.TypingError occurred",
        "The Closest": {
            "ID": 6633,
            "Words": "numba core error typingerror use np random randint"
        },
        "Second Closest": {
            "ID": 13922,
            "Words": "numpi linalg linalgerror singular matrix error tri solv"
        }
    },
    "100": {
        "Test Input": "Python No module named myModule",
        "The Closest": {
            "ID": 5478,
            "Words": "modul name mxnet"
        },
        "Second Closest": {
            "ID": 2560,
            "Words": "googl colab modul name pymorphy"
        }
    },
    "101": {
        "Test Input": "Getting TypeError: 'value' object cannot be interpreted as an integer Error",
        "The Closest": {
            "ID": 6176,
            "Words": "list object attribut valu error"
        },
        "Second Closest": {
            "ID": 2650,
            "Words": "ad valu empti list typeerror"
        }
    },
    "102": {
        "Test Input": "AttributeError: module 'vehicle' has no attribute 'gas_tank_volume'",
        "The Closest": {
            "ID": 15947,
            "Words": "attribut error use webbrows modul"
        },
        "Second Closest": {
            "ID": 17452,
            "Words": "attributeerror modul pyproj attribut cr"
        }
    },
    "103": {
        "Test Input": "OSError: [Errno 22] Invalid argument: 'downloads/project/jquery.js?v=1.4.3'",
        "The Closest": {
            "ID": 13410,
            "Words": "oserror errno invalid argument tri save edit workbook save"
        },
        "Second Closest": {
            "ID": 16955,
            "Words": "messag invalid argument user data directori alreadi use error initi chrome chromedriv selenium"
        }
    },
    "104": {
        "Test Input": "IndexError: list index out of range (my_list)[0]",
        "The Closest": {
            "ID": 23433,
            "Words": "fibonacci indexerror list index rang"
        },
        "Second Closest": {
            "ID": 13920,
            "Words": "indexerror list index rang"
        }
    },
    "105": {
        "Test Input": "python GEKKO Solution Not Found",
        "The Closest": {
            "ID": 18587,
            "Words": "ktrain importerror dll load fail specifi modul could found"
        },
        "Second Closest": {
            "ID": 11409,
            "Words": "winerror system find specifi file"
        }
    },
    "106": {
        "Test Input": "NotADirectoryError in python",
        "The Closest": {
            "ID": 11964,
            "Words": "\u00e4\u00ec read googl sheet file use panda result traceback error"
        },
        "Second Closest": {
            "ID": 4917,
            "Words": "error read cv panda googl drive url"
        }
    },
    "107": {
        "Test Input": "python openpyxl module font attribute gives AttributeError",
        "The Closest": {
            "ID": 12339,
            "Words": "get modul attribut error compil pi"
        },
        "Second Closest": {
            "ID": 888,
            "Words": "resolv error modul umap attribut umap tri instal reinstal umap work"
        }
    },
    "108": {
        "Test Input": "PySpark: TypeError: 'Row' object is not callable : when using .contains",
        "The Closest": {
            "ID": 35,
            "Words": "pyspark typeerror column object callabl use contain"
        },
        "Second Closest": {
            "ID": 8355,
            "Words": "contain pyspark sql typeerror column object callabl"
        }
    },
    "109": {
        "Test Input": "python NLTK LookupError (resource_not_found)",
        "The Closest": {
            "ID": 21130,
            "Words": "ctype error argv"
        },
        "Second Closest": {
            "ID": 22926,
            "Words": "latin codec encod charact"
        }
    },
    "110": {
        "Test Input": "ValueError: Field 'age' expected a number but got 'name'",
        "The Closest": {
            "ID": 18761,
            "Words": "get error say test data lesser number featur"
        },
        "Second Closest": {
            "ID": 15639,
            "Words": "error bar singl number seaborn bar"
        }
    },
    "111": {
        "Test Input": "AttributeError: 'list' object has no attribute 'map'",
        "The Closest": {
            "ID": 8332,
            "Words": "typeerror concaten list map list"
        },
        "Second Closest": {
            "ID": 13321,
            "Words": "use pool map list typeerror support instanc list int"
        }
    },
    "112": {
        "Test Input": "MacOS Big Sur NPM Error Can't find Python executable",
        "The Closest": {
            "ID": 269,
            "Words": "npm error find execut maco big sur"
        },
        "Second Closest": {
            "ID": 17788,
            "Words": "pyaudio recogn error find path"
        }
    },
    "113": {
        "Test Input": "python solution to ValueError: could not convert string to float error",
        "The Closest": {
            "ID": 932,
            "Words": "valueerror could convert string float solut"
        },
        "Second Closest": {
            "ID": 22446,
            "Words": "ascii codec encod charact error"
        }
    },
    "114": {
        "Test Input": "Python bottle Error: 413 Request Entity Too Large",
        "The Closest": {
            "ID": 11991,
            "Words": "larg graph_from_plac request osmnx lead timeout error"
        },
        "Second Closest": {
            "ID": 7602,
            "Words": "publish artifact poetri googl artifact registri http error request entiti larg"
        }
    },
    "115": {
        "Test Input": "xml to tfrecord file convertion gives an error",
        "The Closest": {
            "ID": 2754,
            "Words": "code convert give error"
        },
        "Second Closest": {
            "ID": 4747,
            "Words": "solv valueerror convert excel use openpyxl"
        }
    },
    "116": {
        "Test Input": "kafka module pyspark ModuleNotFound",
        "The Closest": {
            "ID": 2249,
            "Words": "error initialis pyspark instal use pip mac"
        },
        "Second Closest": {
            "ID": 17610,
            "Words": "nameerror name acc defin pyspark accumul"
        }
    },
    "117": {
        "Test Input": "python NameError: name 'value' is not defined",
        "The Closest": {
            "ID": 20438,
            "Words": "valu error convert string float"
        },
        "Second Closest": {
            "ID": 2543,
            "Words": "error use dt accessor datetimelik valu"
        }
    },
    "118": {
        "Test Input": "Python multiprocessing: TypeError: cannot pickle 'names' object",
        "The Closest": {
            "ID": 280,
            "Words": "multiprocess typeerror pickl weakref object"
        },
        "Second Closest": {
            "ID": 4920,
            "Words": "picklingerror use multiprocess"
        }
    },
    "119": {
        "Test Input": "ValueError: 'students' must have either 2 or 3 dimensions",
        "The Closest": {
            "ID": 7449,
            "Words": "typeerror method take posit argument given"
        },
        "Second Closest": {
            "ID": 21626,
            "Words": "tensorflow graph error estim valueerror tensor must graph tensor"
        }
    },
    "120": {
        "Test Input": "AttributeError: 'int' object has no attribute 'user_id' project.py",
        "The Closest": {
            "ID": 9667,
            "Words": "redi py attributeerror int object attribut item"
        },
        "Second Closest": {
            "ID": 9828,
            "Words": "gcloud py attributeerror modul enum attribut int flag"
        }
    },
    "121": {
        "Test Input": "pip ImportError: cannot import name 'appdirs'",
        "The Closest": {
            "ID": 24711,
            "Words": "pip importerror import name"
        },
        "Second Closest": {
            "ID": 21361,
            "Words": "anaconda modul error \u00e4\u00fano modul name pip \u00e4\u00f9"
        }
    },
    "122": {
        "Test Input": "NameError: name 'exit' is not defined",
        "The Closest": {
            "ID": 19799,
            "Words": "nameerror name plt defin"
        },
        "Second Closest": {
            "ID": 3808,
            "Words": "nameerror name resampl defin"
        }
    },
    "123": {
        "Test Input": "RuntimeError: CUDA error: invalid device ordinal",
        "The Closest": {
            "ID": 488,
            "Words": "solv runtimeerror cuda error invalid devic ordin"
        },
        "Second Closest": {
            "ID": 23558,
            "Words": "get runtimeerror cuda error invalid argument pytorch"
        }
    },
    "124": {
        "Test Input": "ModuleNotFoundError: No module named 'matplotlib' on mac OS",
        "The Closest": {
            "ID": 7108,
            "Words": "matplotlib import error typeerror expect str byte os pathlik object windowspath"
        },
        "Second Closest": {
            "ID": 9579,
            "Words": "modul name mac os"
        }
    },
    "125": {
        "Test Input": "NameError: name 'istanbul' is not defined",
        "The Closest": {
            "ID": 2620,
            "Words": "nameerror name value defin"
        },
        "Second Closest": {
            "ID": 13874,
            "Words": "nameerror name training_set defin"
        }
    },
    "126": {
        "Test Input": "OSError: [WinError 2] No such file or directory. Could not install packages",
        "The Closest": {
            "ID": 10283,
            "Words": "panda error could instal packag due oserror file directori"
        },
        "Second Closest": {
            "ID": 2971,
            "Words": "valueerror could broadcast input array shape shape"
        }
    },
    "127": {
        "Test Input": "Tkinter IO error when loading a file",
        "The Closest": {
            "ID": 560,
            "Words": "load file tkinter return io error"
        },
        "Second Closest": {
            "ID": 9058,
            "Words": "tkinter valueerror convert second minut"
        }
    },
    "128": {
        "Test Input": "PyCharm permission denied error",
        "The Closest": {
            "ID": 17841,
            "Words": "import turtl pycharm keep get error"
        },
        "Second Closest": {
            "ID": 388,
            "Words": "descript flake error pycharm"
        }
    },
    "129": {
        "Test Input": "TypeError while reeading a CSV file",
        "The Closest": {
            "ID": 14645,
            "Words": "file directori renam file"
        },
        "Second Closest": {
            "ID": 3298,
            "Words": "pyobjc error tri deploy flask app heroku"
        }
    },
    "130": {
        "Test Input": "Value error while viewing a file",
        "The Closest": {
            "ID": 641,
            "Words": "get valu error view file"
        },
        "Second Closest": {
            "ID": 7518,
            "Words": "error display data file valu tooltip folium map"
        }
    },
    "131": {
        "Test Input": "key error when a new list element is added",
        "The Closest": {
            "ID": 9838,
            "Words": "error on_messag tri add reaction"
        },
        "Second Closest": {
            "ID": 20208,
            "Words": "selenium web scrape error element interact"
        }
    },
    "132": {
        "Test Input": "Pip cannot find EnvironmentError metadata",
        "The Closest": {
            "ID": 544,
            "Words": "pip find metadata file"
        },
        "Second Closest": {
            "ID": 7294,
            "Words": "find nest packag"
        }
    },
    "133": {
        "Test Input": "pycharm  exit code -1073740791 (0xC0000409)",
        "The Closest": {
            "ID": 19333,
            "Words": "pycharm process finish exit code interrupt signal sigabrt error"
        },
        "Second Closest": {
            "ID": 7850,
            "Words": "pycharm error process finish exit code xc"
        }
    },
    "134": {
        "Test Input": "Django KeyError",
        "The Closest": {
            "ID": 7912,
            "Words": "django webpack loader asset keyerror"
        },
        "Second Closest": {
            "ID": 21869,
            "Words": "keyerror pagin scrapi"
        }
    },
    "135": {
        "Test Input": "Django new model object raises OperationalError",
        "The Closest": {
            "ID": 20103,
            "Words": "got error tri save object django"
        },
        "Second Closest": {
            "ID": 336,
            "Words": "django new model object"
        }
    },
    "136": {
        "Test Input": "ImportError: No module named data_preprocess",
        "The Closest": {
            "ID": 12826,
            "Words": "importerror modul name configobj"
        },
        "Second Closest": {
            "ID": 1264,
            "Words": "importerror modul name"
        }
    },
    "137": {
        "Test Input": "No columns to parse from file when converting csv to xlsx file",
        "The Closest": {
            "ID": 19165,
            "Words": "urlerror sparqlwrapp sparql queri convert"
        },
        "Second Closest": {
            "ID": 7937,
            "Words": "get keyerror currenc convert"
        }
    },
    "138": {
        "Test Input": "python error: Microsoft Visual C++ 14.0 or greater is required",
        "The Closest": {
            "ID": 4800,
            "Words": "error could find version satisfi requir scikit learn"
        },
        "Second Closest": {
            "ID": 5369,
            "Words": "fix hidden field submitted_bi field requir error django"
        }
    },
    "139": {
        "Test Input": "python IndentationError",
        "The Closest": {
            "ID": 9477,
            "Words": "django admin backend oper error attempt write readonli databas"
        },
        "Second Closest": {
            "ID": 3450,
            "Words": "error tri pickl user defin class"
        }
    },
    "140": {
        "Test Input": "Error while importing ChatBot",
        "The Closest": {
            "ID": 18314,
            "Words": "error import auto_arima pyramid"
        },
        "Second Closest": {
            "ID": 24881,
            "Words": "error import imblearn undersampl"
        }
    },
    "141": {
        "Test Input": "django permission denied to create database",
        "The Closest": {
            "ID": 13726,
            "Words": "django regist tabl auth_us"
        },
        "Second Closest": {
            "ID": 8136,
            "Words": "typeerror unsupport operand type django"
        }
    },
    "142": {
        "Test Input": "Error 'int' object is not subscriptable",
        "The Closest": {
            "ID": 22204,
            "Words": "multipli sequenc non int type float error"
        },
        "Second Closest": {
            "ID": 9029,
            "Words": "error int object subscript"
        }
    },
    "143": {
        "Test Input": "Visual studio code error while fetching extensions",
        "The Closest": {
            "ID": 11809,
            "Words": "disabl samefileerror except shutil copi"
        },
        "Second Closest": {
            "ID": 11069,
            "Words": "error code bad request tri send messag telegram api"
        }
    },
    "144": {
        "Test Input": "Cloudinary [Error 111] on Pythonanywhere",
        "The Closest": {
            "ID": 6347,
            "Words": "valueerror array got array shape instead"
        },
        "Second Closest": {
            "ID": 10406,
            "Words": "error truth valu seri ambigu"
        }
    },
    "145": {
        "Test Input": "casting float to int",
        "The Closest": {
            "ID": 6130,
            "Words": "typeerror support instanc nonetyp float"
        },
        "Second Closest": {
            "ID": 2327,
            "Words": "overflowerror int larg convert float"
        }
    },
    "146": {
        "Test Input": "http error stotipy spotify API",
        "The Closest": {
            "ID": 13649,
            "Words": "schiphol flight api get flight inform get error"
        },
        "Second Closest": {
            "ID": 4602,
            "Words": "ssl error use esri arcgi api"
        }
    },
    "147": {
        "Test Input": "File Not Found using .tif file",
        "The Closest": {
            "ID": 18199,
            "Words": "qpdf give file found error"
        },
        "Second Closest": {
            "ID": 22107,
            "Words": "tox error file found project_nam"
        }
    },
    "148": {
        "Test Input": "Dimension out of range error expected to be in range of [-1, 0], but got 1",
        "The Closest": {
            "ID": 1427,
            "Words": "runtimeerror dimens rang expect rang got"
        },
        "Second Closest": {
            "ID": 16008,
            "Words": "expect dimens rang got"
        }
    },
    "149": {
        "Test Input": "gcloud run deploy gives error \"image must be specified\"",
        "The Closest": {
            "ID": 362,
            "Words": "run gcloud run deploy exactli accord tutori give error imag must specifi"
        },
        "Second Closest": {
            "ID": 1239,
            "Words": "valueerror client secret must web instal app"
        }
    },
    "150": {
        "Test Input": "got NameError in linked list",
        "The Closest": {
            "ID": 12937,
            "Words": "nameerror link list data structur"
        },
        "Second Closest": {
            "ID": 19427,
            "Words": "nameerror use functool partial insid loop"
        }
    },
    "151": {
        "Test Input": "matplotlib gives error with splitted list",
        "The Closest": {
            "ID": 604,
            "Words": "attributeerror tupl object attribut set_xlim matplotlib"
        },
        "Second Closest": {
            "ID": 15915,
            "Words": "dimens matplotlib give error"
        }
    },
    "152": {
        "Test Input": "pandas converting column type to datetime in csv file",
        "The Closest": {
            "ID": 24799,
            "Words": "type error import panda datafram excel file"
        },
        "Second Closest": {
            "ID": 13966,
            "Words": "panda read_excel keyerror read set xlsx file"
        }
    },
    "153": {
        "Test Input": "TypeError: unsupported operand type(s) for +: 'int' and 'str'",
        "The Closest": {
            "ID": 16156,
            "Words": "typeerror miss requir posit argument"
        },
        "Second Closest": {
            "ID": 10838,
            "Words": "sud syntaxerror invalid syntax"
        }
    },
    "154": {
        "Test Input": "TypeError: train_test_split() got an unexpected keyword argument 'traiset'",
        "The Closest": {
            "ID": 8694,
            "Words": "typeerror got unexpect keyword argument object_id_field"
        },
        "Second Closest": {
            "ID": 18237,
            "Words": "syntaxerror invalid syntax"
        }
    },
    "155": {
        "Test Input": "pip install rioxarray gives RuntimeError",
        "The Closest": {
            "ID": 12798,
            "Words": "fix runtimeerror discord bot"
        },
        "Second Closest": {
            "ID": 12952,
            "Words": "runtimeerror instal rioxarray"
        }
    },
    "156": {
        "Test Input": "django makemigrations says no such table",
        "The Closest": {
            "ID": 12956,
            "Words": "make migrat error django tabl"
        },
        "Second Closest": {
            "ID": 20944,
            "Words": "django makemigr error column"
        }
    },
    "157": {
        "Test Input": "Error while giving different parameters with multiclass classificaiton in Keras",
        "The Closest": {
            "ID": 10042,
            "Words": "tensorflow throw incompat shape custom loss function end epoch"
        },
        "Second Closest": {
            "ID": 19289,
            "Words": "kera input rais valu error dimensioon match"
        }
    },
    "158": {
        "Test Input": "pyttsx3 error  while converting to exe",
        "The Closest": {
            "ID": 3194,
            "Words": "attributeerror nonetyp object attribut get_memb"
        },
        "Second Closest": {
            "ID": 10826,
            "Words": "mysql connector mysql connect avail error"
        }
    },
    "159": {
        "Test Input": "TypeError: can only concatenate str (not 'int') to str",
        "The Closest": {
            "ID": 10121,
            "Words": "typeerror int object iter error"
        },
        "Second Closest": {
            "ID": 2409,
            "Words": "typeerror concaten str dict str"
        }
    },
    "160": {
        "Test Input": "NameError: name 'Movie' is not defined in pgzrun/python",
        "The Closest": {
            "ID": 13874,
            "Words": "nameerror name training_set defin"
        },
        "Second Closest": {
            "ID": 14842,
            "Words": "nameerror name integerfield defin"
        }
    },
    "161": {
        "Test Input": "Keras ValueError: Shapes (None, 1) and (None, 100, 100, 200) are incompatible",
        "The Closest": {
            "ID": 12967,
            "Words": "kera valueerror shape none none incompat"
        },
        "Second Closest": {
            "ID": 3464,
            "Words": "error construct multioutput model kera"
        }
    },
    "162": {
        "Test Input": "python giving nonetype object is not iterable",
        "The Closest": {
            "ID": 7366,
            "Words": "pyautocad give ungoogl error"
        },
        "Second Closest": {
            "ID": 9010,
            "Words": "panda datafram merg give error"
        }
    },
    "163": {
        "Test Input": "Error - input expected at most 2 argument, got 5",
        "The Closest": {
            "ID": 12971,
            "Words": "error input expect argument got"
        },
        "Second Closest": {
            "ID": 4055,
            "Words": "typeerror input expect argument got"
        }
    },
    "164": {
        "Test Input": "Crawling data with Selenium throwing TimeoutException",
        "The Closest": {
            "ID": 12972,
            "Words": "crawl data selenium throw error timeoutexcept"
        },
        "Second Closest": {
            "ID": 7519,
            "Words": "throw error selenium"
        }
    },
    "165": {
        "Test Input": "while parsing JSON TypeError: list indices must be integers or slices, not str",
        "The Closest": {
            "ID": 15028,
            "Words": "pars id_token authlib"
        },
        "Second Closest": {
            "ID": 6673,
            "Words": "report pars error pli caller parser"
        }
    },
    "166": {
        "Test Input": "ModuleNotFoundError: No module named 'Networkx'",
        "The Closest": {
            "ID": 11440,
            "Words": "modul name sphinx error"
        },
        "Second Closest": {
            "ID": 21479,
            "Words": "plotli attributeerror figur object attribut update_layout"
        }
    },
    "167": {
        "Test Input": "Python modulenotfounderror for an installed library",
        "The Closest": {
            "ID": 11710,
            "Words": "instal librari backtrad error"
        },
        "Second Closest": {
            "ID": 12583,
            "Words": "error instal mglearn"
        }
    },
    "168": {
        "Test Input": "unresolved reference in python",
        "The Closest": {
            "ID": 484,
            "Words": "one function call anoth function class fix unresolv refer error"
        },
        "Second Closest": {
            "ID": 9571,
            "Words": "navigablestr error refer happen"
        }
    },
    "169": {
        "Test Input": "ValueError: cannot reshape array of size 700 into shape (50,50,7)",
        "The Closest": {
            "ID": 18733,
            "Words": "get error reshap array size shape"
        },
        "Second Closest": {
            "ID": 6184,
            "Words": "valueerror reshap array size shape"
        }
    },
    "170": {
        "Test Input": "TypeError: bytes like object is required not str",
        "The Closest": {
            "ID": 8538,
            "Words": "typeerror memoryview byte like object requir jpegimagefil"
        },
        "Second Closest": {
            "ID": 4160,
            "Words": "typeerror miss requir posit argument self"
        }
    },
    "171": {
        "Test Input": "ValueError: could not convert string to float: 'price'",
        "The Closest": {
            "ID": 3692,
            "Words": "attributeerror type object datetim datetim attribut datetim"
        },
        "Second Closest": {
            "ID": 681,
            "Words": "typeerror got unexpect keyword argument as_tupl"
        }
    },
    "172": {
        "Test Input": "python 'bool' object is not subscriptable",
        "The Closest": {
            "ID": 21107,
            "Words": "typeerror fit_transform miss requir posit argument raw_docu"
        },
        "Second Closest": {
            "ID": 23174,
            "Words": "range_state_int repres numpi dtype"
        }
    },
    "173": {
        "Test Input": "pygraphviz_layout gives KeyError: Node not in graph",
        "The Closest": {
            "ID": 13004,
            "Words": "keyerror node graph use even though node networkx graph"
        },
        "Second Closest": {
            "ID": 5745,
            "Words": "socketio keyerror session disconnect"
        }
    },
    "174": {
        "Test Input": "error when reading from csv with datatable",
        "The Closest": {
            "ID": 24154,
            "Words": "read csv file"
        },
        "Second Closest": {
            "ID": 14618,
            "Words": "errno file directori test_user"
        }
    },
    "175": {
        "Test Input": "pytest AttributeError: 'Function' object has no attribute 'get_customer'",
        "The Closest": {
            "ID": 13056,
            "Words": "pytest attributeerror function object attribut get_mark"
        },
        "Second Closest": {
            "ID": 16032,
            "Words": "attributeerror function object attribut summari"
        }
    },
    "176": {
        "Test Input": "got error  __init__() got an unexpected keyword argument 'movie_Artist' in python",
        "The Closest": {
            "ID": 6274,
            "Words": "get miss requir posit argument error"
        },
        "Second Closest": {
            "ID": 22684,
            "Words": "typeerror tupl indic must integ slice dict"
        }
    },
    "177": {
        "Test Input": "ImportError: cannot import name 'Pooling' from 'sklearn'",
        "The Closest": {
            "ID": 5445,
            "Words": "sklearn typeerror got unexpect keyword argument"
        },
        "Second Closest": {
            "ID": 10533,
            "Words": "sklearn typeerror got unexpect keyword argument n_split"
        }
    },
    "178": {
        "Test Input": "typeerror: 'str' object is not callable",
        "The Closest": {
            "ID": 10919,
            "Words": "tf kera to_categor typeerror model fit"
        },
        "Second Closest": {
            "ID": 11924,
            "Words": "indexerror index bound axi size"
        }
    },
    "179": {
        "Test Input": "chromedriver not working while web scraping filenotfound error",
        "The Closest": {
            "ID": 5716,
            "Words": "selenium find element xpath work error java"
        },
        "Second Closest": {
            "ID": 1999,
            "Words": "error run selenium webdriv proxi"
        }
    },
    "180": {
        "Test Input": "ascii' codec can't decode byte 0xe7 in position 0: ordinal not in range(256)",
        "The Closest": {
            "ID": 20749,
            "Words": "typeerror rang indic must integ slice tupl"
        },
        "Second Closest": {
            "ID": 16741,
            "Words": "get rang error code see detail"
        }
    },
    "181": {
        "Test Input": "ValueError: could not convert string to float, after removing unwanted characters in column (Pandas)",
        "The Closest": {
            "ID": 13099,
            "Words": "valueerror could convert string float remov unwant charact column panda"
        },
        "Second Closest": {
            "ID": 12236,
            "Words": "mysql error insert ukranian charact"
        }
    },
    "182": {
        "Test Input": "encoding error \"utf-8\" python",
        "The Closest": {
            "ID": 18022,
            "Words": "typeerror support instanc"
        },
        "Second Closest": {
            "ID": 7562,
            "Words": "django admin django rest framework drf"
        }
    },
    "183": {
        "Test Input": "Pycharm: Unresolved reference error when I open a project",
        "The Closest": {
            "ID": 13123,
            "Words": "pycharm unresolv refer error ide open work project"
        },
        "Second Closest": {
            "ID": 14831,
            "Words": "unresolv refer django error pycharm"
        }
    },
    "184": {
        "Test Input": "python break outside loop error in for loop",
        "The Closest": {
            "ID": 24742,
            "Words": "run script vba iwshshell error"
        },
        "Second Closest": {
            "ID": 24453,
            "Words": "error loop loop work properli"
        }
    },
    "185": {
        "Test Input": "cannot multiply matrix numpy",
        "The Closest": {
            "ID": 6002,
            "Words": "error divis zero spell sugest"
        },
        "Second Closest": {
            "ID": 9307,
            "Words": "selenium headless error element interact"
        }
    },
    "186": {
        "Test Input": "python3 installing mysqlclient gives error",
        "The Closest": {
            "ID": 14364,
            "Words": "get error mysqlclient instal instal"
        },
        "Second Closest": {
            "ID": 1604,
            "Words": "fix error instal dotenv uvloop"
        }
    },
    "187": {
        "Test Input": "scraping HTML span by class gives error",
        "The Closest": {
            "ID": 21135,
            "Words": "importerror modul name bs scrape hub"
        },
        "Second Closest": {
            "ID": 11734,
            "Words": "get error scrape date"
        }
    },
    "188": {
        "Test Input": "python path no such file or directory",
        "The Closest": {
            "ID": 17998,
            "Words": "permissionerror errno permiss deni text_fil"
        },
        "Second Closest": {
            "ID": 17060,
            "Words": "ioerror errno file directori file directori"
        }
    },
    "189": {
        "Test Input": "AttributeError: 'Request' object has no attribute 'question'",
        "The Closest": {
            "ID": 23228,
            "Words": "attributeerror request object attribut get"
        },
        "Second Closest": {
            "ID": 16621,
            "Words": "attributeerror modul object attribut request"
        }
    },
    "190": {
        "Test Input": "ValueError: expected dense_x to have shape (57,) but got array with shape (4,)",
        "The Closest": {
            "ID": 22238,
            "Words": "valueerror error check input expect dense_ dimens got array shape"
        },
        "Second Closest": {
            "ID": 18938,
            "Words": "valueerror error check input expect dense_input shape got array shape"
        }
    },
    "191": {
        "Test Input": "sorting df by date gives check for duplicates error",
        "The Closest": {
            "ID": 9774,
            "Words": "check duplic letter string convert hashtabl keyerror"
        },
        "Second Closest": {
            "ID": 18939,
            "Words": "check duplic error tri sort datafram datetime"
        }
    },
    "192": {
        "Test Input": "AttributeError occurs trying to copy content from a file to another",
        "The Closest": {
            "ID": 8876,
            "Words": "get attributeerror"
        },
        "Second Closest": {
            "ID": 17441,
            "Words": "oserror errno bad file descriptor occur tri write csv"
        }
    },
    "193": {
        "Test Input": "when I try to reach a character it says TypeError: string indices must be integers",
        "The Closest": {
            "ID": 17644,
            "Words": "index string get syntaxerror"
        },
        "Second Closest": {
            "ID": 23246,
            "Words": "syntax error newlin charact within string liter"
        }
    },
    "194": {
        "Test Input": "Python nested exception statement in another exception try catch",
        "The Closest": {
            "ID": 12925,
            "Words": "except error list comprehens"
        },
        "Second Closest": {
            "ID": 13875,
            "Words": "error perform tri except part"
        }
    },
    "195": {
        "Test Input": "TypeError: __init__() missing 1 required positional argument: 'on_click'",
        "The Closest": {
            "ID": 13233,
            "Words": "typeerror open_fil miss requir posit argument self"
        },
        "Second Closest": {
            "ID": 23761,
            "Words": "local variabl referenc assign assign global variabl"
        }
    },
    "196": {
        "Test Input": "PdfReadError: EOF marker not found while parsing word document in python",
        "The Closest": {
            "ID": 18996,
            "Words": "tri pars word document get pdfreaderror eof marker found"
        },
        "Second Closest": {
            "ID": 14211,
            "Words": "found syntax error make list fix"
        }
    },
    "197": {
        "Test Input": "flask error on heroku gives error while opening an excel file",
        "The Closest": {
            "ID": 12492,
            "Words": "keyerror flask app upload csv csv heroku"
        },
        "Second Closest": {
            "ID": 1712,
            "Words": "issu load excel workbook xlwing local applic microsoft excel app found"
        }
    },
    "198": {
        "Test Input": "math.sin() gives error",
        "The Closest": {
            "ID": 22390,
            "Words": "error tri solv ode use scipi"
        },
        "Second Closest": {
            "ID": 13536,
            "Words": "code hex decim give error fix"
        }
    },
    "199": {
        "Test Input": "Python raises ValueError when comparing int and array value",
        "The Closest": {
            "ID": 19171,
            "Words": "creat float array list rais valu error"
        },
        "Second Closest": {
            "ID": 18722,
            "Words": "understand kera error typeerror valu pass paramet shape datatyp float list allow valu int int"
        }
    },
    "200": {
        "Test Input": "request import gives error while webscraping",
        "The Closest": {
            "ID": 19142,
            "Words": "webscrap request import error"
        },
        "Second Closest": {
            "ID": 22837,
            "Words": "pydev import request give error unresolv import request"
        }
    },
    "201": {
        "Test Input": "PermissionError: [Errno 13] Permission denied: 'video.mp4'",
        "The Closest": {
            "ID": 10400,
            "Words": "speech recognit recognize_googl microphon"
        },
        "Second Closest": {
            "ID": 4280,
            "Words": "beauti soup error"
        }
    }
}